{% set name = "neuromorphic-drivers" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neuromorphic_drivers-{{ version }}.tar.gz
  sha256: 88e3288f4b540507a7a0e24befe9a6f77d4ac92a86946ff77832120c40dc9605

build:
  entry_points:
    - neuromorphic-drivers-install-udev-rules = neuromorphic_drivers:install_udev_rules_program
    - ndls = neuromorphic_drivers:print_device_list
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.2.3,<2                  # [build_platform != target_platform]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.2.3,<2
    - numpy
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - neuromorphic_drivers
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Neuromorphic devices drivers
  home: https://github.com/neuromorphicsystems/neuromorphic-rs
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - Tobias-Fischer
